function net = train_denoising_model(trainSet, validationSet, cfg)
%TRAIN_DENOISING_MODEL Train using recording-independent validation data.
if isempty(trainSet.inputs) || isempty(validationSet.inputs)
    error('AudioDenoising:EmptyDataset', ...
        'Training and validation datasets must contain spectrogram segments.');
end
assert(isempty(intersect(unique(trainSet.recording),unique(validationSet.recording))), ...
    'AudioDenoising:Leakage','Training and validation recordings overlap.');
layers = build_mask_cnn(size(trainSet.inputs,1:3));
options = trainingOptions('adam','InitialLearnRate',cfg.initialLearnRate, ...
    'MaxEpochs',cfg.maxEpochs,'MiniBatchSize',cfg.miniBatchSize, ...
    'Shuffle','every-epoch','ValidationData', ...
    {validationSet.inputs,validationSet.targets}, ...
    'ExecutionEnvironment',cfg.executionEnvironment,'Verbose',false);
net = trainNetwork(trainSet.inputs,trainSet.targets,layers,options);
end
